name: Deploy Red Room Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/deploy_frontend.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  IMAGE_NAME: red-room-frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      ##################################################
      #               AZURE & ACR LOGIN
      ##################################################

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ vars.AZURE_ACR_NAME }}

      ##################################################
      #             BUILD & DEPLOY TO ACR
      ##################################################

      - name: Build Image
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=${{ vars.NEXT_PUBLIC_API_URL }} -t ${{ vars.AZURE_ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }} frontend

      - name: Push Image
        run: |
          docker push ${{ vars.AZURE_ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }}

      - name: Deploy Container App
        run: |
          az containerapp update --name red-room-frontend --resource-group red-room --image ${{ vars.AZURE_ACR_NAME }}.azurecr.io/$IMAGE_NAME:${{ github.sha }}
